version: '3'

services:
    web:
      image: nginx:latest
      ports:
        - "8070:80"
      volumes:
        - ./nginx/conf.d/:/etc/nginx/conf.d/
        - ./symfony/:/var/www/html/
      networks:
        - symfony
      depends_on:
        - app
    app:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - ./symfony/:/var/www/html/
      networks:
        - symfony
      depends_on:
        mysql:
          condition: service_healthy
    mysql:
      image: mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: symfony_db
      healthcheck:
        test: mysqladmin ping -h 127.0.0.1 -u root --password=root
        start_period: 2s
        interval: 2s
        timeout: 2s
        retries: 100
      volumes:
        - backend_mysql:/var/lib/mysql
      networks:
        - symfony
volumes:
  backend_mysql:
networks:
  symfony:
